#!/bin/sh
#
# postrm
#

emailrelay_purge()
{
	local spool="/var/spool/emailrelay"
	local rundir="/run/emailrelay"
	rmdir "$spool" 2>/dev/null # deliberately fails if spooled messages exist
	rmdir "$rundir" 2>/dev/null
}

#DEBHELPER#

if test "$1" = "purge"
then
	emailrelay_purge
fi
exit 0

