#!/bin/sh
#
# postinst
#

emailrelay_setup()
{
	# use the init script for some post-install setup
	local init="/etc/init.d/emailrelay"
	if test -e "$init" -a ! -x "$init"
	then
		chmod +x "$init"
	fi
	"$init" setup
}

emailrelay_setup

#DEBHELPER#

exit 0

