#!/usr/bin/perl
#
# SPDX-FileCopyrightText: 2026 Graeme Walker <graeme_walker@users.sourceforge.net>
# SPDX-License-Identifier: GPL-3.0-or-later
# 
# Copyright (c) 2026 Graeme Walker <graeme_walker@users.sourceforge.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ===
#
# ConfigStatus.pm
#
# Provides 'switches' and 'vars' parsed out of one or
# more "config.status" files (as generated by an autoconf
# configure script).
#
# Synopsis:
#  use ConfigStatus ;
#  my $cs = new ConfigStatus() ;
#  $cs->parse( ConfigStatus::find($basedir) ) ;
#  $cs->parse( ConfigStatus::find($basedir,$subdir) , $subdir ) ;
#  $cs->varsref()->{foo} = "foo1" ;
#  $cs->varsref("sub/dir")->{foo} = "foo2" ;
#  my %vars = $cs->vars() ;
#  my %switches = $cs->switches() ;
#  my %subvars = $cs->vars( $subdir ) ;
#  my %subswitches = $cs->switches( $subdir ) ;
#
# The "basedir" is typically the project root or a vpath build
# directory. The optional "subdir" is the relative path to a
# sub-project, with its own configure script.
#
# See also: AutoMakeParser
#

use strict ;
use IO::File ;
use File::Basename ;

package ConfigStatus ;

sub new
{
	my ( $classname ) = @_ ;
	my $this = bless {
		m_files => {} , # subdir=>{path,switches,vars}
	} , $classname ;
	return $this ;
}

sub load
{
	my ( $this , $switches , $vars , $subdir ) = @_ ;
	$subdir ||= "" ;
	$this->{m_files}->{$subdir} = {
			path => "" ,
			switches => $switches ,
			vars => $vars ,
		} ;
}

sub find
{
	# Finds a "config.status" file in the directory that is the
	# concatenation of the given base combined with the optional
	# sub-directory, while allowing for the base directory to be
	# a vpath build directory.
	my ( $basedir , $subdir , $optional ) = @_ ;
	$basedir ||= "." ;
	$subdir ||= "" ;

	my $path1 = _pathjoin( $basedir , $subdir , "config.status" ) ;
	my $path2 = _pathjoin( $basedir , ".." , $subdir , "config.status" ) ;
	if( -e $path1 )
	{
		return $path1 ;
	}
	elsif( -e $path2 )
	{
		return $path2 ;
	}
	else
	{
		my $dir1 = File::Basename::dirname( $path1 ) ;
		my $dir2 = File::Basename::dirname( $path2 ) ;
		die "error: no config.status file found in [$dir1] or [$dir2]: run \"configure\" first\n" unless $optional ;
		return undef ;
	}
}

sub _bestkey
{
	my ( $this , $subdir ) = @_ ;
	return _bestkey_imp( $subdir , keys %{$this->{m_files}} ) ;
}

sub _bestkey_imp
{
	my ( $subdir , @keys ) = @_ ;
	my $bestkey = "" ;
	for my $key ( @keys )
	{
		if( length($key) <= length($subdir) &&
			length($key) >= length($bestkey) &&
			$key eq substr($subdir,0,length($key)) )
		{
			$bestkey = $key ;
		}
	}
	return $bestkey ;
}

sub vars
{
	# Returns the variables hash by value, optionally for a
	# particular sub-directory.
	#
	# Uses the lookup key which has the longest leading sub-string
	# match compared to the given subdir.
	#
	my ( $this , $subdir ) = @_ ;
	$subdir ||= "" ;
	my $key = $this->_bestkey( $subdir ) ;
	my $varsref = $this->{m_files}->{$key}->{vars} ;
	return %$varsref ;
}

sub varsref
{
	# Returns the variables hash by reference so that values can be modified.
	my ( $this , $subdir ) = @_ ;
	$subdir ||= "" ;
	my $key = $this->_bestkey( $subdir ) ;
	return $this->{m_files}->{$key}->{vars} ;
}

sub switches
{
	# Returns the switches hash by value.
	my ( $this , $subdir ) = @_ ;
	$subdir ||= "" ;
	my $key = $this->_bestkey( $subdir ) ;
	my $switchesref = $this->{m_files}->{$key}->{switches} ;
	return %$switchesref ;
}

sub switchesref
{
	# Returns the switches hash by reference so that values can be modified.
	my ( $this , $subdir ) = @_ ;
	$subdir ||= "" ;
	my $key = $this->_bestkey( $subdir ) ;
	return $this->{m_files}->{$key}->{switches} ;
}

sub switch
{
	my ( $this , $switch_name , $subdir  ) = @_ ;
	return $this->switchesref($subdir)->{$switch_name} ;
}

sub parse
{
	# Parses the given "config.status" file. The results are
	# stored internally. The sub-directory parameter is used as
	# a lookup key.
	my ( $this , $cspath , $subdir ) = @_ ;

	$cspath ||= "config.status" ;
	$subdir ||= "" ;
	my ($switches,$vars) = _parse_imp( $cspath ) ;
	_expand( $vars ) ;
	warn "warning: config.status file [$cspath] does not define a version" if( !exists $vars->{VERSION} ) ;
	die "error: already parsed" if exists($this->{m_files}->{$subdir}) ;
	$this->{m_files}->{$subdir} = {
			path => $cspath ,
			switches => $switches ,
			vars => $vars ,
		} ;
}

sub _parse_imp
{
	my ( $cspath ) = @_ ;
	my $switches = {} ;
	my $vars = {} ;
	my $line_number = 0 ;
	my $fh = new IO::File( $cspath , "r" ) or die "error: cannot open [$cspath]: " . lc($!) . "\n" ;
	while(<$fh>)
	{
		chomp( my $line = $_ ) ;
		$line_number++ ;
		while( $line =~ m/\\$/ )
		{
			$line = substr( $line , 0 , length($line)-2 ) ; # remove doublequote-backslash
			my $next = <$fh> ;
			$line_number++ ;
			chomp( $next ) ;
			$next =~ s/^"// ;
			$line .= $next ;
		}
		my ( $k , $v ) = ( $line =~ m/^S\["([^"]+)"\]="([^"]*)"\s*$/ ) ;
		if( $k && defined($v) )
		{
			if( $k =~ m/_TRUE$/ )
			{
				( my $kk = $k ) =~ s/_TRUE$// ;
				my $vv = ( $v eq "" ? 1 : 0 ) ;
				$switches->{$kk} = $vv ;
			}
			elsif( $k =~ m/_FALSE$/ )
			{
				( my $kk = $k ) =~ s/_FALSE$// ;
				my $vv = ( $v eq "" ? 0 : 1 ) ;
				$switches->{$kk} = $vv ;
			}
			else
			{
				$vars->{$k} = $v ;
			}
		}
	}
	return ( $switches , $vars ) ;
}

sub _expand
{
	my ( $vars ) = @_ ;
	# expand eg. "0_${onetwo}" where onetwo="${one}_${two}" giving "0_1_2"
	for my $k ( sort keys %$vars )
	{
		my $v = $vars->{$k} ;
		for my $i ( 0 .. 10 )
		{
			my ( $subkey ) = ( $v =~ m/\$\{([^}]*)\}/ ) ;
			if( $subkey && exists($vars->{$subkey}) )
			{
				my $new = $vars->{$subkey} ;
				$v =~ s/\$\{$subkey\}/$new/ ;
			}
		}
		$vars->{$k} = $v ;
	}
}

sub _pathjoin
{
	my $path = join( "/" , grep {$_} @_ ) ;
	$path =~ s:^\./:: ;
	return $path ;
}

1 ;
