#
## SPDX-FileCopyrightText: 2026 Graeme Walker <graeme_walker@users.sourceforge.net>
## SPDX-License-Identifier: GPL-3.0-or-later
#

work_scripts = \
	make-manifest.sh \
	make-setup.sh \
	run_doxygen.pl \
	make-format \
	make-sphinx \
	make2cmake \
	make2cdb \
	make-release-notes \
	make2unity \
	mbedtlsbuild.pl \
	git-pre-commit \
	libresslbuild.pl \
	qtbuild.pl \
	winbuild.pm \
	winbuildall.bat \
	winbuild-assembly.pl \
	AutoMakeParser.pm \
	BuildInfo.pm \
	cmake.pm \
	CompilationDatabase.pm \
	ConfigStatus.pm

EXTRA_DIST = \
	$(work_scripts)

noinst_SCRIPTS = \
	$(work_scripts)

