#!/usr/bin/env perl
#
# SPDX-FileCopyrightText: 2026 Graeme Walker <graeme_walker@users.sourceforge.net>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# make2cdb
#
# Parses automake files throughout the source tree and generates
# a "compilation database" file on stdout.
#
# See also: https://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# Usage: make2cdb [--list] [<base-dir> [<config-status> [<base-to-top>]]]
#
# Eg:
#  $ cd src
#  $ ../libexec/make2cdb > compile_commands.json
#  $ ../libexec/make2cdb --list | xargs clang-tidy -p .
#

use strict ;
use Cwd ;
use File::Find ;
use File::Basename ;
use File::Spec ;
use File::Copy ;
use Getopt::Long ;
BEGIN { unshift @INC , dirname($0) }
use ConfigStatus ;
use CompilationDatabase ;

my %opt = () ;
GetOptions( \%opt , "list" , "test" , "debug" ) or die "$0: usage error\n" ;
my $cfg_show_list = exists( $opt{list} ) ;
my $cfg_test_mode = exists( $opt{test} ) ;
my $cfg_debug = exists( $opt{debug} ) ;
$CompilationDatabase::debug = $cfg_debug ;

my $base_dir = @ARGV ? $ARGV[0] : dirname($0)."/../src" ;
my $config_status = @ARGV > 1 ? $ARGV[1] : undef ;
my $base_to_top = @ARGV > 2 ? $ARGV[2] : ".." ;

my $cs = new ConfigStatus() ;
$cs->parse( ConfigStatus::find($config_status) ) ;
$cs->varsref()->{top_srcdir} = $base_to_top ;
$cs->varsref()->{top_builddir} = "." ;

my $cdb = new CompilationDatabase( $base_dir , $cs , {test_mode=>$cfg_test_mode,full_paths=>1} ) ;
if( $cfg_show_list )
{
	print join( "\n" , $cdb->list() , "" ) ;
}
elsif( $cfg_test_mode )
{
	print join( "" , $cdb->stanzas() ) ;
}
else
{
	print "[\n" ;
	print join( ",\n" , $cdb->stanzas() ) ;
	print "]\n" ;
}

