#!/usr/bin/env perl
#
# SPDX-FileCopyrightText: 2026 Graeme Walker <graeme_walker@users.sourceforge.net>
# SPDX-License-Identifier: GPL-3.0-or-later
# 
# Copyright (c) 2026 Graeme Walker <graeme_walker@users.sourceforge.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ===
#
# run_doxygen.pl
#
# Used from doc/Makefile to run doxygen. Works correctly in a vpath build by
# creating a doxygen configuration file on the fly that has the correct
# directory paths. Copies a dummy html file if use of doxygen is not enabled.
#
# The ephemeral doxygen config file ("doxygen.cfg") is created by running
# "doxygen -g", with variable substitution applied by the "Doxyfile" package
# (see "Doxyfile.pm").
#
# usage: run_doxygen.pl <enabled-if-yes> <srcdir> <builddir> [<outdir> [<cfg-out>]]
#
# eg: run_doxygen.pl "$(GCONFIG_DOXYGEN)" "$(top_srcdir)" "$(top_builddir)" doxygen doxygen.cfg
#

use strict ;
use File::Basename ;
use File::Copy ;
use lib ( File::Basename::dirname($0) ) ;
use Doxyfile ;

my $enabled_if_yes = $ARGV[0] ;
my $top_srcdir = $ARGV[1] ;
my $top_builddir = $ARGV[2] ;
my $subdir = $ARGV[3] || "doxygen" ;
my $doxyfile_cfg = $ARGV[4] || "doxygen.cfg" ;

my $cfg = {
	COLOUR => "blue" ,
	SRC => "glib,gssl,gnet,gauth,gverifiers,gfilters,gstore,gsmtp,gpop,main/doxygen.h" ,
	PROJECT_NAME => "E-MailRelay Source" ,
	PROJECT_LOGO => "" ,
	##INPUT => "..." ,
	HTML_OUTPUT => "doxygen" ,
	FILE_PATTERNS => [ "*.h" , "*.cpp" ] ,
	EXCLUDE_PATTERNS => [ "*handles.h" , "*handles.cpp" ] ,
	EXCLUDE_SYMBOLS => [ "*Imp" ] ,
	HTML_HEADER => "" ,
	HTML_FOOTER => "" ,
	HTML_EXTRA_STYLESHEET => [ "__TOP_SRC__/doc/emailrelay-doxygen.css" ] ,
	DISABLE_INDEX => "YES" ,
	GENERATE_TREEVIEW => "YES" ,
	TOC_INCLUDE_HEADINGS => "6" ,
	SHOW_FILES => "YES" ,
	SEARCHENGINE => "YES" ,
	LAYOUT_FILE => "" ,
} ;

if( "$enabled_if_yes" eq "yes" )
{
	# create the config file
	my $df = new Doxyfile( $cfg ) ;
	$df->run() ;
	$df->purge() ;
	$df->substitute({
			"__TOP_SRC__" => $top_srcdir ,
			"__TOP_BUILD__" => $top_builddir ,
		}) ;
	$df->write( $doxyfile_cfg ) ;

	# run doxygen
	unlink( "doxygen.out" ) ;
	unlink( "$subdir/index.html" ) ;
	system( "doxygen \"$doxyfile_cfg\" > doxygen.out 2>&1" ) ;
	if( ! -f "$subdir/index.html" )
	{
		die "error: run_doxygen.pl: no html output generated by doxygen: check doxygen.out\n" ;
	}
}
else
{
	mkdir( $subdir ) ;
	my $fh = new IO::File( "$subdir/index.html" , "w" ) or die ;
	print $fh <DATA> ;
}

__DATA__
<!DOCTYPE html>
<html>
<head>
<title>E-MailRelay source code documentation missing</title>
<link rel="stylesheet" href="../emailrelay.css" type="text/css">
</head>
<body>
<div class="div-main">
<h1>E-MailRelay Source Code</h1>
<p>No <a class="a-href" href="https://www.doxygen.org">doxygen</a> documentation available locally, try <a class="a-href" href="https://emailrelay.sourceforge.net/doxygen/namespaces.html">online</a>.</p>
</div>
</body>
</html>
