#
## SPDX-FileCopyrightText: 2026 Graeme Walker <graeme_walker@users.sourceforge.net>
## SPDX-License-Identifier: GPL-3.0-or-later
#

EXTRA_DIST = \
	acinclude.m4 \
	ax_cxx_compile_stdcxx.m4 \
	ax_cxx_compile_stdcxx.m4.license \
	ax_require_defined.m4 \
	ax_require_defined.m4.license \
	pkg.m4 \
	pkg.m4.license
