.\" SPDX-FileCopyrightText: 2026 Graeme Walker <graeme_walker@users.sourceforge.net>
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH EMAILRELAY-SUBMIT 1 local
.SH NAME
emailrelay-submit \- a submission utility for emailrelay
.SH SYNOPSIS
.B emailrelay-submit
[--help] [--verbose] [--spool-dir
.IR spool-directory ]
[--from
.IR from-address ]
.RI [ to-address \ ...]
.SH DESCRIPTION
.I emailrelay-submit
is a utility which reads an RFC-822 e-mail message from the standard
input and writes it into the
.B E-MailRelay
spool directory.
.LP
The verbose option causes the path of the new content file
to be printed.
.SH OPTIONS
.TP
.B \-f \fI<envelope-from-address>\fR
.PD 0
.TP
.PD
.B \-\-from \fI<envelope-from-address>\fR
Sets the envelope 'from' address. If not supplied the envelope 'from' address is derived from the originator headers in the message content, or \fIanonymous\fR if none.
.TP
.B \-h
.PD 0
.TP
.PD
.B \-\-help
Shows help text and exits.
.TP
.B \-x \fI<file>\fR
.PD 0
.TP
.PD
.B \-\-input-file \fI<file>\fR
Reads the specified input file, ignoring the standard input stream.
.TP
.B \-s \fI<dir>\fR
.PD 0
.TP
.PD
.B \-\-spool-dir \fI<dir>\fR
Specifies the spool directory.
.TP
.B \-v
.PD 0
.TP
.PD
.B \-\-verbose
Prints the full path of the content file.
.TP
.B \-b
.PD 0
.TP
.PD
.B \-\-bcc-split
Submits messages separately for each \fIBcc:\fR recipient.
.TP
.B \-d
.PD 0
.TP
.PD
.B \-\-content-date
Adds a \fIDate:\fR content header if there is none.
.TP
.B \-F
.PD 0
.TP
.PD
.B \-\-content-from
Adds a \fIFrom:\fR content header using the envelope-from address given by \fI\fR\fI--from\fR\fI\fR, replacing any existing \fIFrom:/Sender:\fR headers.
.TP
.B \-I
.PD 0
.TP
.PD 0
.B \-\-content-message-id
.TP
.PD
.B \-\-content-message-id=\fI<domain-part>\fR
Adds a \fIMessage-ID:\fR content header if there is none.
.TP
.B \-t
.PD 0
.TP
.PD
.B \-\-content-to
Adds a \fITo:\fR content header using the envelope-to addresses given by \fI\fR\fI--to\fR\fI\fR and/or trailing command-line arguments, replacing any existing \fITo:/cc:/bcc:\fR headers.
.TP
.B \-c
.PD 0
.TP
.PD
.B \-\-copy
Copies the envelope file into all sub-directories of the main spool directory.
.TP
.B \-n
.PD 0
.TP
.PD
.B \-\-filename
Prints the name of the content file.
.TP
.PD
.B \-\-to \fI<envelope-to-address>\fR
Adds an envelope 'to' address. Trailing command-line arguments can also be used for envelope 'to' addresses.
.TP
.B \-V
.PD 0
.TP
.PD
.B \-\-version
Prints the version number and exits.
.TP
.B \-a \fI<name>\fR
.PD 0
.TP
.PD
.B \-\-auth \fI<name>\fR
Sets the authentication value in the envelope file.
.TP
.B \-B
.PD 0
.TP
.PD
.B \-\-body
Treats the standard input or \fI--input-file\fR as body text with no headers.
.TP
.B \-C \fI<base64>\fR
.PD 0
.TP
.PD
.B \-\-content \fI<base64>\fR
Adds a line of content. This can be a header line, a blank line or a line of the body text. The first blank line separates headers from the body. The option value should be base64 encoded.
.TP
.B \-i \fI<name>\fR
.PD 0
.TP
.PD
.B \-\-from-auth-in \fI<name>\fR
Sets the 'from-auth-in' value in the envelope file.
.TP
.B \-o \fI<name>\fR
.PD 0
.TP
.PD
.B \-\-from-auth-out \fI<name>\fR
Sets the 'from-auth-out' value in the envelope file.
.TP
.B \-N
.PD 0
.TP
.PD
.B \-\-no-stdin
Ignores the standard-input. Typically used with \fI\fR\fI--content\fR\fI\fR. Not needed with \fI\fR\fI--input-file\fR\fI\fR.
.SH SEE ALSO
.BR emailrelay (1),
.BR emailrelay-passwd (1)
.SH AUTHOR
Graeme Walker <graeme_walker@users.sourceforge.net>
