#
## SPDX-FileCopyrightText: 2026 Graeme Walker <graeme_walker@users.sourceforge.net>
## SPDX-License-Identifier: GPL-3.0-or-later
#

EXTRA_DIST = \
	emailrelay-icon.ico \
	emailrelay-icon.png \
	emailrelay-icon.svg \
	emailrelay-icon-small.png \
	emailrelay-icon-tiny.png

e_icon_DATA = emailrelay-icon.png

