#
## SPDX-FileCopyrightText: 2026 Graeme Walker <graeme_walker@users.sourceforge.net>
## SPDX-License-Identifier: GPL-3.0-or-later
#

EXTRA_DIST = \
	alice.crt \
	alice.key \
	bob.crt \
	bob.key \
	carol.crt \
	carol.key \
	dave.crt \
	dave.key \
	malory.crt \
	malory.key \
	trent.crt \
	trent.key \
	trudy.crt \
	trudy.key

