
name: emailrelay-build

on:
  push:
    branches:
      - main

jobs:

  tarball:
    if: |
      contains(github.event.head_commit.message, '[tarball]')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: install-tools
        run: "sudo apt-get install -y autoconf automake libtool"
      - name: make-dist
        working-directory: emailrelay-src
        run: |
          ./autogen.sh
          ./configure
          make dist
          for f in *.tar.gz; do
            mv "$f" "${f%.tar.gz}-src.tar.gz"
          done
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: source-tarball
          path: "emailrelay-src/emailrelay-*-src.tar.gz"
          if-no-files-found: error

  packages:
    if: |
      contains(github.event.head_commit.message, '[packages]')
    name: package-for-${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: debian12
            container: debian:bookworm-slim
            package_type: deb
            make_args: DISTRO=+deb12 deb
            path_pattern: "emailrelay-src/emailrelay_*.deb"
          - distro: debian13
            container: debian:trixie-slim
            package_type: deb
            make_args: DISTRO=+deb13 deb
            path_pattern: "emailrelay-src/emailrelay_*.deb"
          - distro: ubuntu2404
            container: ubuntu:24.04
            package_type: deb
            make_args: DISTRO=+ub2404 deb
            path_pattern: "emailrelay-src/emailrelay_*.deb"
          - distro: ubuntu2604
            container: ubuntu:26.04
            package_type: deb
            make_args: DISTRO=+ub2604 deb
            path_pattern: "emailrelay-src/emailrelay_*.deb"
          - distro: redhat9
            container: rockylinux:9
            package_type: rpm
            make_args: DISTRO=.rh9 rpm
            path_pattern: "emailrelay-src/emailrelay*.rpm"
          - distro: redhat10
            container: rockylinux/rockylinux:10
            package_type: rpm
            make_args: DISTRO=.rh10 rpm
            path_pattern: "emailrelay-src/emailrelay*.rpm"
          - distro: alpine320
            container: alpine:3.20
            package_type: apk
            make_args: DISTRO=.alpine320 APK_UNITY=1 apk
            path_pattern: "emailrelay-src/emailrelay*.apk"
    container:
      image: ${{ matrix.container }}
    steps:
      - name: tools-deb
        if: matrix.package_type == 'deb'
        run: |
          apt-get update
          apt-get install -y build-essential git devscripts debhelper dh-exec libssl-dev libpam0g-dev pkg-config
      - name: tools-rpm
        if: matrix.package_type == 'rpm'
        run: |
          dnf groupinstall -y "Development Tools"
          dnf install -y git rpm-build rpmdevtools systemd-rpm-macros openssl-devel pam-devel pkgconfig
      - name: tools-apk
        if: matrix.package_type == 'apk'
        run: |
          apk update
          apk add build-base autoconf automake git alpine-sdk abuild openssl-dev pkgconfig
      - name: checkout
        uses: actions/checkout@v4
      - name: make-package
        working-directory: emailrelay-src
        run: |
          echo "sha=${{ github.sha }}"
          ./autogen.sh
          ./configure.sh
          echo "make [${{ matrix.make_args }}]"
          make ${{ matrix.make_args }}
      - name: upload-package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.distro }}
          path: ${{ matrix.path_pattern }}
          if-no-files-found: error
      - name: apk-copy-key
        if: matrix.package_type == 'apk'
        run: |
          VERSION=$(cat emailrelay-src/VERSION)
          cp ~/.abuild/*rsa.pub emailrelay-$VERSION-${{ matrix.distro }}.rsa.pub
      - name: apk-upload-key
        if: matrix.package_type == 'apk'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.distro }}-key
          path: *.rsa.pub
          if-no-files-found: error

  winbuild:
    runs-on: windows-latest
    if: |
      contains(github.event.head_commit.message, '[winbuild]')
    env:
      Platform: x64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: download-libs
        working-directory: ./emailrelay-src
        run: "libexec/winbuildall.bat download"
      - name: set-version
        shell: cmd
        working-directory: ./emailrelay-src
        run: |
          set /p VERSION=<VERSION
          echo VERSION=[%VERSION%]
          echo VERSION=%VERSION%>>%GITHUB_ENV%
      - name: msvc-environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: winbuildall
        working-directory: ./emailrelay-src
        run: "libexec/winbuildall.bat release"
      - name: compress
        shell: cmd
        working-directory: ./emailrelay-src
        run: |
          7z a emailrelay-%VERSION%-w64.zip .\emailrelay-windows-x64-release\*
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: "emailrelay-src/emailrelay-*-w64.zip"

  winxp:
    if: |
      contains(github.event.head_commit.message, '[winxp]')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: install-tools
        run: "sudo apt-get install -y autoconf automake libtool g++-mingw-w64-i686-posix zip"
      - name: configure
        working-directory: emailrelay-src
        run: |
          ./autogen.sh
          ./configure.sh -M -w32
      - name: make-mbedtls
        working-directory: emailrelay-src
        run: |
          cmake --fresh -DMBEDTLS_CONFIG_FILE=mbedtls_user_config.h -B mbedtls_build -S mbedtls-3.6.7 --toolchain toolchain-w32.cmake
          cmake --build mbedtls_build --target lib
      - name: make
        working-directory: emailrelay-src
        run: |
          make -j
          make -C src/main strip map
      - name: assemble
        working-directory: emailrelay-src
        run: |
          perl libexec/winbuild-assembly.pl --winxp
          ls -lR emailrelay-*-winxp
      - name: zip
        working-directory: emailrelay-src
        run: |
          zip -r emailrelay-`cat VERSION`-winxp32.zip emailrelay-`cat VERSION`-winxp
          ls -l *.zip
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: source-tarball
          path: "emailrelay-src/emailrelay-*-winxp32.zip"
          if-no-files-found: error

  website:
    if: |
      contains(github.event.head_commit.message, '[website]')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: install-tools
        run: "sudo apt-get install -y python3-sphinx python3-myst-parser pandoc"
      - name: run-sphinx
        working-directory: emailrelay-src
        run: |
          perl libexec/make-sphinx --website --examples-dir=bin . website
      - name: tar
        working-directory: emailrelay-src
        run: |
          tar -C website/out -cf website-`cat VERSION`.tar .
          gzip website-*.tar
          ls -l website-*.tar.gz
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: "emailrelay-src/website-*.tar.gz"
          if-no-files-found: error

  release:
    name: release
    runs-on: ubuntu-latest
    needs: [tarball, packages, winxp, website]
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: download-artifacts
        uses: actions/download-artifact@v4
        with:
          path: files/
          merge-multiple: true
          #pattern: ... # all uploaded artifacts by default
      - name: get-version
        id: get_version
        run: |
          echo "VERSION=$(cat emailrelay-src/VERSION | xargs)" >> $GITHUB_ENV
          echo "version=$(cat emailrelay-src/VERSION | xargs)" >> $GITHUB_OUTPUT
          echo "vversion=v$(cat emailrelay-src/VERSION | xargs)" >> $GITHUB_OUTPUT
      - name: make-release-notes
        run: "cd files && ../emailrelay-src/libexec/make-release-notes ../emailrelay-src"
        continue-on-error: true
      - name: list-files
        run: "ls -lR files/"
        continue-on-error: true
      - name: log-version
        run: |
          echo version=v${{ steps.get_version.outputs.version }}
          echo tag=${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || steps.get_version.outputs.vversion }}
        continue-on-error: true
      - name: attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            files/*.deb
            files/*.rpm
            files/*.apk
            files/*.zip
      - name: release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || steps.get_version.outputs.vversion }}
          draft: ${{ !startsWith(github.ref, 'refs/tags/') }}
          prerelease: ${{ contains(steps.get_version.outputs.version, 'rc') }}
          working_directory: files
          files: "*"
          body_path: files/RELEASE.md

  winbuild_x64:
    runs-on: windows-latest
    if: |
      contains(github.event.head_commit.message, '[winbuild-old]')
    env:
      Platform: x64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cmake-x64-release
        run: "cmake --fresh -A x64 -B x64 -S ."
      - name: winbuild-x64-release
        run: "cmake --build x64 --config release"
      - name: archive-windows-x64-release
        uses: actions/upload-artifact@v4
        with:
          name: emailrelay-windows-x64-release
          path: emailrelay-windows-x64-release

  winbuild_x64_import:
    runs-on: windows-latest
    if: |
      contains(github.event.head_commit.message, '[winbuild-import]')
    env:
      Platform: x64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: import-libs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download libs-windows-x64-release-static-r41
          7z x qt-w64.zip "-ox64/qt-bin-x64"
          7z x qt-tr-w64.zip "-ox64/qt-build-x64-release/qttranslations/translations"
          7z x mbedtls-w64.zip "-ox64/mbedtls-build-x64-release"
          7z x libressl-w64.zip "-ox64/libressl-build-x64-release"
      - name: cmake-x64-release
        run: "cmake --fresh -A x64 -B x64 -S ."
      - name: winbuild-x64-release
        run: "cmake --build x64 --config release"
      - name: archive-windows-x64-release
        uses: actions/upload-artifact@v4
        with:
          name: emailrelay-windows-x64-release
          path: emailrelay-windows-x64-release

  winbuild_x64_export:
    runs-on: windows-latest
    if: |
      contains(github.event.head_commit.message, '[winbuild-export]')
    permissions:
      contents: write
    env:
      Platform: x64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cmake-x64-release
        run: "cmake --fresh -A x64 -B x64 -S ."
      - name: winbuild-x64-release
        run: "cmake --build x64 --config release"
      - name: archive-windows-x64-release
        uses: actions/upload-artifact@v4
        with:
          name: emailrelay-windows-x64-release
          path: emailrelay-windows-x64-release
      - name: compress-qt
        run: |
          cd x64/qt-bin-x64 && 7z a -mx9 "../../qt-w64.zip" *
      - name: compress-qt-tr
        run: |
          cd x64/qt-build-x64-release/qttranslations/translations && 7z a -mx9 "../../../../qt-tr-w64.zip" *
      - name: compress-mbedtls
        run: |
          cd x64/mbedtls-build-x64-release && 7z a -mx9 "../../mbedtls-w64.zip" *
      - name: compress-libressl
        run: |
          cd x64/libressl-build-x64-release && 7z a -mx9 "../../libressl-w64.zip" *
      - name: export-libs
        uses: softprops/action-gh-release@v2
        with:
          tag_name: libs-windows-x64-release-static-r${{ github.run_number }}
          name: libs r${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            qt-w64.zip
            qt-tr-w64.zip
            mbedtls-w64.zip
            libressl-w64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  winbuild_x86:
    runs-on: windows-latest
    if: |
      contains(github.event.head_commit.message, '[winbuild-x86]')
    env:
      Platform: x86
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cmake-x86-release
        run: "cmake --fresh -A Win32 -B x86 -S ."
      - name: winbuild-x86-release
        run: "cmake --build x86 --config release"
      - name: archive-windows-x86-release
        uses: actions/upload-artifact@v4
        with:
          name: emailrelay-windows-x86-release
          path: emailrelay-windows-x86-release

  winbuild_dynamic_gui:
    if: |
      contains(github.event.head_commit.message, '[winbuild-dynamic]')
    runs-on: windows-latest
    env:
      Platform: x64
    steps:
      - uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.3'
          archives: 'qtbase qttools qttranslations'
          cache: true
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            emailrelay-src
      - name: make2cmake
        working-directory: ./emailrelay-src
        run: "perl libexec/make2cmake --no-help --no-mbedtls --qt-find-package"
      - name: cmake-prepare
        working-directory: ./emailrelay-src
        run: "cmake --fresh -A x64 -B build -S ."
      - name: cmake-build-gui
        working-directory: ./emailrelay-src
        run: "cmake --build build --config release --target emailrelay-gui"
      - name: deploy
        working-directory: ./emailrelay-src/build/src/gui/main
        run: "windeployqt --no-compiler-runtime emailrelay-gui.exe"
      - name: archive
        uses: actions/upload-artifact@v4
        with:
          name: emailrelay-windows-x64-dynamic
          path: ./emailrelay-src/build/src/gui/main

  winbuild_x64_nogui:
    runs-on: windows-latest
    if: |
      contains(github.event.head_commit.message, '[winbuild-nogui]')
    env:
      Platform: x64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cmake-x64-release
        run: "cmake --fresh -DOPTIONS=--no-gui -A x64 -B x64 -S ."
      - name: winbuild-x64-release
        run: "cmake --build x64 --config release"
      - name: archive-windows-x64-release
        uses: actions/upload-artifact@v4
        with:
          name: emailrelay-windows-x64-nogui
          path: |
            x64/emailrelay-build-x64-release/src/main/x64/emailrelay.exe
            x64/emailrelay-build-x64-release/src/main/x64/emailrelay-submit.exe
            x64/emailrelay-build-x64-release/src/main/x64/emailrelay-service.exe

