name: winbuildall

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  Platform: x64

jobs:
  build_job:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cmake
        run: cmake .
      - name: build
        run: cmake --build .
      - name: archive
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: |
            emailrelay-bin-x64/src/main/release/*.exe
            emailrelay-bin-x64/src/gui/release/*.exe
