name: winbuildall

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_job:
    runs-on: windows-latest
    steps:
      - name: build_step
        uses: actions/checkout@v4
		    run: %ComSpec% /D /E:ON /V:OFF /S /C "CALL winbuildall.bat"
