name: winbuildall

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: cmake
        run: cmake .
      - name: cmake_build
        run: cmake --build .
