# GitHub workflow for emailrelay-build

name: winbuildall

on:
  push:
    branches:
      - main

jobs:

  winbuild_x64:
    runs-on: windows-latest
    if: |
      contains(github.event.head_commit.message, '[build]')
    env:
      Platform: x64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cmake-x64-release
        run: cmake --fresh -A x64 -B x64 -S .
      - name: winbuild-x64-release
        run: cmake --build x64 --config release
      - name: archive-windows-x64-release
        uses: actions/upload-artifact@v4
        with:
          name: emailrelay-windows-x64-release
          path: emailrelay-windows-x64-release

  winbuild_x64_import:
    runs-on: windows-latest
    if: |
      contains(github.event.head_commit.message, '[build-import]')
    env:
      Platform: x64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: import-libs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download libs-windows-x64-release-static-r38
          7z x qt-w64.zip "-ox64/qt-bin-x64"
          7z x qt-tr-w64.zip "-ox64/qt-build-x64-release/qttranslations/translations"
          7z x mbedtls-w64.zip "-ox64/mbedtls-build-x64-release"
          7z x libressl-w64.zip "-ox64/libressl-build-x64-release"
      - name: cmake-x64-release
        run: cmake --fresh -A x64 -B x64 -S .
      - name: winbuild-x64-release
        run: cmake --build x64 --config release
      - name: archive-windows-x64-release
        uses: actions/upload-artifact@v4
        with:
          name: emailrelay-windows-x64-release
          path: emailrelay-windows-x64-release

  winbuild_x64_export:
    runs-on: windows-latest
    if: |
      contains(github.event.head_commit.message, '[build-export]')
    permissions:
      contents: write
    env:
      Platform: x64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cmake-x64-release
        run: cmake --fresh -A x64 -B x64 -S .
      - name: winbuild-x64-release
        run: cmake --build x64 --config release
      - name: archive-windows-x64-release
        uses: actions/upload-artifact@v4
        with:
          name: emailrelay-windows-x64-release
          path: emailrelay-windows-x64-release
      - name: compress-qt
        run: |
          cd x64/qt-bin-x64 && 7z a -mx9 "../../qt-w64.zip" *
      - name: compress-qt-tr
        run: |
          cd x64/qt-build-x64-release/qttranslations/translations && 7z a -mx9 "../../../../qt-tr-w64.zip" *
      - name: compress-mbedtls
        run: |
          cd x64/mbedtls-build-x64-release && 7z a -mx9 "../../mbedtls-w64.zip" *
      - name: compress-libressl
        run: |
          cd x64/libressl-build-x64-release && 7z a -mx9 "../../libressl-w64.zip" *
      - name: export-libs
        uses: softprops/action-gh-release@v2
        with:
          tag_name: libs-windows-x64-release-static-r${{ github.run_number }}
          name: libs r${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            qt-w64.zip
            qt-tr-w64.zip
            mbedtls-w64.zip
            libressl-w64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  winbuild_x86:
    runs-on: windows-latest
    if: |
      contains(github.event.head_commit.message, '[build-x86]')
    env:
      Platform: x86
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cmake-x86-release
        run: cmake --fresh -A Win32 -B x86 -S .
      - name: winbuild-x86-release
        run: cmake --build x86 --config release
      - name: archive-windows-x86-release
        uses: actions/upload-artifact@v4
        with:
          name: emailrelay-windows-x86-release
          path: emailrelay-windows-x86-release

  winbuild_dynamic_gui:
    if: |
      contains(github.event.head_commit.message, '[build-dynamic]')
    runs-on: windows-latest
    env:
      Platform: x64
    steps:
      - uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.3'
          archives: 'qtbase qttools qttranslations'
          cache: true
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            emailrelay-src
      - name: make2cmake
        working-directory: ./emailrelay-src
        run: perl libexec/make2cmake --no-help --no-mbedtls --qt-find-package
      - name: cmake-prepare
        working-directory: ./emailrelay-src
        run: cmake --fresh -A x64 -B build -S .
      - name: cmake-build-gui
        working-directory: ./emailrelay-src
        run: cmake --build build --config release --target emailrelay-gui
      - name: deploy
        working-directory: ./emailrelay-src/build/src/gui/main
        run: windeployqt --no-compiler-runtime emailrelay-gui.exe
      - name: archive
        uses: actions/upload-artifact@v4
        with:
          name: emailrelay-windows-x64-dynamic
          path: ./emailrelay-src/build/src/gui/main

  winbuild_x64_nogui:
    runs-on: windows-latest
    if: |
      contains(github.event.head_commit.message, '[build-nogui]')
    env:
      Platform: x64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cmake-x64-release
        run: cmake --fresh -DOPTIONS=--no-gui -A x64 -B x64 -S .
      - name: winbuild-x64-release
        run: cmake --build x64 --config release
      - name: archive-windows-x64-release
        uses: actions/upload-artifact@v4
        with:
          name: emailrelay-windows-x64-nogui
          path: |
            x64/emailrelay-build-x64-release/src/main/x64/emailrelay.exe
            x64/emailrelay-build-x64-release/src/main/x64/emailrelay-submit.exe
            x64/emailrelay-build-x64-release/src/main/x64/emailrelay-service.exe

